/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'rgb(var(--primary-rgb) / <alpha-value>)',
        'primary-deep': 'var(--color-primary-deep)',
        'on-primary': 'var(--color-on-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'primary-fixed': 'rgb(var(--primary-fixed-rgb) / <alpha-value>)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        background: 'var(--color-background)',
        'on-background': 'var(--color-on-background)',
        surface: 'rgb(var(--surface-rgb) / <alpha-value>)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'surface-subtle': 'rgb(var(--surface-subtle-rgb) / <alpha-value>)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-low': 'rgb(var(--surface-container-low-rgb) / <alpha-value>)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-lowest': 'rgb(var(--surface-container-lowest-rgb) / <alpha-value>)',
        'surface-variant': 'var(--color-surface-variant)',
        'border-light': 'var(--color-border-light)',
        'outline-variant': 'var(--color-outline-variant)',
        secondary: 'var(--color-secondary)',
        tertiary: 'var(--color-tertiary)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'success-vibrant': 'var(--color-success-vibrant)',
        error: 'rgb(var(--error-rgb) / <alpha-value>)',
        'error-container': 'rgb(var(--error-container-rgb) / <alpha-value>)',
        'on-error-container': 'var(--color-on-error-container)',
        accent: 'rgb(var(--accent-rgb) / <alpha-value>)',
        'accent-soft': 'rgb(var(--accent-soft-rgb) / <alpha-value>)',
        inbox: 'rgb(var(--inbox-rgb) / <alpha-value>)',
        'inbox-soft': 'rgb(var(--inbox-soft-rgb) / <alpha-value>)',
        glow: 'var(--color-glow)',
        gold: '#ffc107',
        charcoal: '#1a1a1a',
        'dark-iron': '#000000',
        ash: '#8e9099',
        smoke: '#f5f6fa',
        'teal-action': 'var(--color-teal-action)',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Text"',
          '"SF Pro Display"',
          'Inter',
          'Heebo',
          '"Segoe UI"',
          'Roboto',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        display: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Display"',
          '"SF Pro Text"',
          'Inter',
          'Heebo',
          '"Segoe UI"',
          'sans-serif',
        ],
        body: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Text"',
          'Inter',
          'Heebo',
          '"Segoe UI"',
          'sans-serif',
        ],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      fontSize: {
        'display-xl': [
          'clamp(2.5rem, 6vw, 5rem)',
          { lineHeight: '0.95', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'display-lg': [
          'clamp(2rem, 4.5vw, 3.375rem)',
          { lineHeight: '1.05', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'headline-lg': [
          'clamp(1.75rem, 3vw, 2.5rem)',
          { lineHeight: '1.15', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-lg-mobile': [
          '1.75rem',
          { lineHeight: '1.15', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-md': [
          '1.125rem',
          { lineHeight: '1.35', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'body-lg': ['1.125rem', { lineHeight: '1.56', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': [
          '0.875rem',
          { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' },
        ],
        'label-sm': [
          '0.75rem',
          { lineHeight: '1.5', letterSpacing: '0.02em', fontWeight: '500' },
        ],
        micro: [
          '0.625rem',
          { lineHeight: '1.2', letterSpacing: '0.04em', fontWeight: '500' },
        ],
      },
      spacing: {
        'margin-mobile': '1rem',
        'margin-desktop': '2.5rem',
        'mobile-nav': 'calc(5.5rem + env(safe-area-inset-bottom, 0px))',
        gutter: '2rem',
        'container-max': '1440px',
        section: '3.5rem',
      },
      borderRadius: {
        none: '0',
        sm: '0.75rem',
        DEFAULT: '1rem',
        md: '1.15rem',
        lg: '1.35rem',
        xl: '1.5rem',
        '2xl': '1.65rem',
        '3xl': '1.85rem',
        full: '9999px',
        switch: '20px',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        nav: 'var(--shadow-nav)',
        glow: 'var(--shadow-glow)',
        boutique: 'var(--shadow-boutique)',
        'inner-glow': 'var(--shadow-inner-glow)',
        float: 'var(--shadow-soft)',
        soft: 'var(--shadow-soft)',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      animation: {
        'fade-up': 'fadeUp 0.7s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'soft-pulse': 'softPulse 5s ease-in-out infinite',
        'page-enter': 'pageEnter 0.22s cubic-bezier(0.22, 1, 0.36, 1) both',
        'list-in': 'listIn 0.35s cubic-bezier(0.22, 1, 0.36, 1) both',
        'status-flash': 'statusFlash 0.48s cubic-bezier(0.22, 1, 0.36, 1)',
        'status-pop': 'statusPop 0.4s cubic-bezier(0.22, 1, 0.36, 1)',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        softPulse: {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '0.55' },
        },
        pageEnter: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        listIn: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        statusFlash: {
          '0%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgb(var(--primary-rgb) / 0)' },
          '35%': {
            transform: 'scale(1.04)',
            boxShadow: '0 0 0 4px rgb(var(--primary-rgb) / 0.22)',
          },
          '100%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgb(var(--primary-rgb) / 0)' },
        },
        statusPop: {
          '0%': { opacity: '0', transform: 'scale(0.88)' },
          '60%': { opacity: '1', transform: 'scale(1.05)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
