/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'rgb(var(--primary-rgb) / <alpha-value>)',
        'primary-deep': 'var(--color-primary-deep)',
        'on-primary': 'var(--color-on-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'primary-fixed': 'rgb(var(--primary-fixed-rgb) / <alpha-value>)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        background: 'var(--color-background)',
        'on-background': 'var(--color-on-background)',
        surface: 'rgb(var(--surface-rgb) / <alpha-value>)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'surface-subtle': 'rgb(var(--surface-subtle-rgb) / <alpha-value>)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-low': 'rgb(var(--surface-container-low-rgb) / <alpha-value>)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-lowest': 'rgb(var(--surface-container-lowest-rgb) / <alpha-value>)',
        'surface-variant': 'var(--color-surface-variant)',
        'border-light': 'var(--color-border-light)',
        'outline-variant': 'var(--color-outline-variant)',
        secondary: 'var(--color-secondary)',
        tertiary: 'var(--color-tertiary)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'success-vibrant': 'var(--color-success-vibrant)',
        error: 'rgb(var(--error-rgb) / <alpha-value>)',
        'error-container': 'rgb(var(--error-container-rgb) / <alpha-value>)',
        'on-error-container': 'var(--color-on-error-container)',
        accent: 'rgb(var(--accent-rgb) / <alpha-value>)',
        'accent-soft': 'rgb(var(--accent-soft-rgb) / <alpha-value>)',
        inbox: 'rgb(var(--inbox-rgb) / <alpha-value>)',
        'inbox-soft': 'rgb(var(--inbox-soft-rgb) / <alpha-value>)',
        glow: 'var(--color-glow)',
        gold: '#ffc000',
        charcoal: '#202020',
        'dark-iron': '#181818',
        ash: '#7d7d7d',
        smoke: '#f5f5f5',
      },
      fontFamily: {
        display: ['"Roboto Condensed"', 'Heebo', 'system-ui', 'sans-serif'],
        body: ['Roboto', 'Heebo', 'system-ui', 'sans-serif'],
        mono: ['Roboto', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-xl': [
          'clamp(2.5rem, 6vw, 5rem)',
          { lineHeight: '0.92', letterSpacing: '0.02em', fontWeight: '400' },
        ],
        'display-lg': [
          'clamp(2rem, 4.5vw, 3.375rem)',
          { lineHeight: '1.0', letterSpacing: '0.02em', fontWeight: '400' },
        ],
        'headline-lg': [
          'clamp(1.75rem, 3vw, 2.5rem)',
          { lineHeight: '1.15', letterSpacing: '0.04em', fontWeight: '400' },
        ],
        'headline-lg-mobile': [
          '1.75rem',
          { lineHeight: '1.15', letterSpacing: '0.04em', fontWeight: '400' },
        ],
        'headline-md': [
          '1.125rem',
          { lineHeight: '1.37', letterSpacing: '0.06em', fontWeight: '400' },
        ],
        'body-lg': ['1.125rem', { lineHeight: '1.56', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': [
          '0.875rem',
          { lineHeight: '1.4', letterSpacing: '0.08em', fontWeight: '400' },
        ],
        'label-sm': [
          '0.75rem',
          { lineHeight: '1.83', letterSpacing: '0.08em', fontWeight: '500' },
        ],
        micro: [
          '0.625rem',
          { lineHeight: '1', letterSpacing: '0.14em', fontWeight: '400' },
        ],
      },
      spacing: {
        'margin-mobile': '1rem',
        'margin-desktop': '2.5rem',
        gutter: '2rem',
        'container-max': '1440px',
        section: '3.5rem',
      },
      borderRadius: {
        none: '0',
        sm: '2px',
        DEFAULT: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '9999px',
        switch: '20px',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        nav: 'var(--shadow-nav)',
        glow: 'var(--shadow-glow)',
        boutique: 'var(--shadow-boutique)',
        'inner-glow': 'var(--shadow-inner-glow)',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      animation: {
        'fade-up': 'fadeUp 0.7s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'soft-pulse': 'softPulse 5s ease-in-out infinite',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        softPulse: {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '0.55' },
        },
      },
    },
  },
  plugins: [],
}
